name: 'github-action-build-push-github-package-registry'
description: Build and Push a Docker image to GitHub Package Registry
author: Sebastien Thebert
inputs:
  github_package_registry_login:
    description: Login to connect to Github Package Registry.
    required: true
  github_package_registry_password:
    description: Password (Personal access token) to connect to Github Package Registry.
    require: true
  image_name:
    description: name of the image.  Example - my_awesome_image
    require: true
  build_context:
    description: the path in your repo that will serve as the build context.
    require: false
  dockerfile_path:
    description: the full path (including the filename) to the dockerfile that you want to build
    require: false
outputs:
  DOCKER_IMAGE_NAME:
    description: Docker image name
  DOCKER_IMAGE_URL:
    description: Docker image URL in Github Package Registry
branding:
  color: 'blue'
  icon: 'layers'
runs:
  using: 'docker'
  image: 'Dockerfile'
